name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Get dependencies
      working-directory: ./todo
      run: go mod download
      
    - name: Build binaries
      working-directory: ./todo
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        mkdir -p dist
        
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${VERSION}" -o dist/todo-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${VERSION}" -o dist/todo-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${VERSION}" -o dist/todo-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${VERSION}" -o dist/todo-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${VERSION}" -o dist/todo-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w -X main.version=${VERSION}" -o dist/todo-windows-arm64.exe .
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          todo/dist/todo-*
        body: |
          ## 🚀 Smart Todo CLI Release
          
          ### Installation
          
          **Linux (x64):**
          ```bash
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/todo-linux-amd64 -o todo
          chmod +x todo
          sudo mv todo /usr/local/bin/
          ```
          
          **macOS (Intel):**
          ```bash
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/todo-darwin-amd64 -o todo
          chmod +x todo
          sudo mv todo /usr/local/bin/
          ```
          
          **macOS (Apple Silicon):**
          ```bash
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/todo-darwin-arm64 -o todo
          chmod +x todo
          sudo mv todo /usr/local/bin/
          ```
          
          **Windows:**
          Download `todo-windows-amd64.exe` and add to your PATH.
          
          ### Features
          - 🎯 Smart task management with intelligent insights
          - 📊 Advanced filtering and productivity analytics
          - 🧠 Smart suggestions and cleanup automation
          - ⚡ Lightning-fast performance
          - 🎨 Beautiful command-line interface
          
          See the [README](https://github.com/${{ github.repository }}/blob/main/README.md) for complete usage instructions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
